### ISSUE TITLE
10.12.4

### ISSUE THREAD

**Issue by steadystatic** [jessedoyle/isight-cli#4] opened 2017-03-30 13:29 UTC
Disabling isight works in latest 10.12.4, however trying to re-enable it, despite the script running without error the camera still remains disabled.

**Comment by jessedoyle** [comment] 2017-03-30 19:29
Hey, thanks for using `isight-cli`!

Are you able to run these commands and paste the output?:

```bash
isight status
sudo isight status
```

I suspect you'll see output like:

```
> isight status                                                                                                                                                                                              
iSight Status: Enabled
> sudo isight status                                                                                                                                                                                         
iSight Status: Disabled
```

This occurs because `isight-cli` currently isn't very smart about what permissions it is run under. As a workaround, you could run the `isight on` command both with _and_ without `sudo`. 

Of course, any PRs would be welcome to help fix this issue :)

**Comment by jessedoyle** [comment] 2017-03-30 19:37
Failing that, you can always manually remove the restriction profile from `System Preferences > Profiles` on recent Mac OS versions:

<img width="669" alt="screen shot 2017-03-30 at 1 35 22 pm" src="https://cloud.githubusercontent.com/assets/6474230/24522773/dca86448-154d-11e7-98ea-460700c47274.png">

**Comment by steadystatic** [comment] 2017-03-30 19:47
Thank you for checking this out! Will definitely look into this deeper this weekend and see if I can help debug and make a PR possibly.

![screen shot 2017-03-30 at 1 45 48 pm](https://cloud.githubusercontent.com/assets/130587/24523153/5757d8da-154f-11e7-84a8-c066d5379c84.png)

I'll check on the Profiles in settings next. Thanks again!

**Comment by jessedoyle** [comment] 2017-03-30 19:55
Hmm, that's odd! I'm not sure what's going on here then. But you should always be able to manually remove the profile so it shouldn't be of concern.

I'll have to install `10.12.4` on my machine and test it out (currently on `10.12.3`). Thanks for the report!

**Comment by jessedoyle** [comment] 2017-05-29 05:10
Hey @steadystatic - I was never able to replicate this issue (I tried with `10.12.4` and I currently have `10.12.6` installed now).

For now I'm going to close this issue. But I'm still not certain what occurred in your case. If you have any additional insight or you can reproduce the issue, please comment and I'll reopen the issue!

Thanks!

**Closed as completed by jessedoyle** 2017-05-29 05:10 UTC
